### ISSUE TITLE
关于 [train/valid/test]_top_64_candidates.tsv 文件

### ISSUE THREAD

**Issue by wutaiqiang** [Alibaba-NLP/MuVER#1]
你好！
我想请问一下，https://github.com/Alibaba-NLP/MuVER/blob/d1da6eba7d467a66c5e369c9fa95988adbf28b0c/muver/multi_view/data_loader.py#L283 这一行的 *_top_64_candidates.tsv 这个是自己处理得到的？还是zeshel原始论文里面说的使用tf-idf检索得到的64个候选？

**Comment by wutaiqiang** [comment]
@horseee 谢谢

**Comment by horseee** [comment]
Hi @wutaiqiang ,

DataLoader部分的代码是同时为一阶段bi-encoder和二阶段cross-encoder设计的。在一阶段中不会使用到这部分的信息，可以看dataloader的__getitem__部分代码

>https://github.com/Alibaba-NLP/MuVER/blob/d1da6eba7d467a66c5e369c9fa95988adbf28b0c/muver/multi_view/data_loader.py#L332-L340

*_top_64_candidates.tsv为MuVER一阶段生成的candidates。这部分的代码在第一次处理的时候会遇到一些问题，我们会尽快修复这儿的bug。

**Comment by horseee** [comment]
Hi @wutaiqiang ,

上面所提及的bug已经修复。

**Comment by wutaiqiang** [comment]
好嘞，明白了，感谢~
