### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by wutaiqiang** [Alibaba-NLP/MuVER#2]
你好！
https://github.com/Alibaba-NLP/MuVER/blob/28761d988eca21a6c334f2e33562799773894bc5/muver/multi_view/train.py#L221
这一行，应该改为：
if args.do_train and args.local_rank in [0, -1]:

按照代码逻辑，local rank不是0/1的进程 log==None，对于他们来说并没有checkpoint_path这个参数

**Comment by horseee** [comment]
Solved
